'use strict';

/**
 * ml/train.js — Random Forest training for the HTSI model layer.
 *
 * Runs entirely in Node.js (ml-random-forest), keeping the backend
 * Node/Express-only. Called by scripts/trainModel.js.
 *
 * Anti-leakage: the caller passes rows already sorted by timestamp; the
 * split here is chronological (earlier → train, later → test), so no
 * future information reaches training. Preprocessing is ml/features.js —
 * the same module used at live-prediction time.
 */

const { RandomForestRegression } = require('ml-random-forest');
const { FEATURE_NAMES } = require('./features');
const { regressionMetrics, classificationMetrics } = require('./evaluation');
const { saveModelArtifacts, loadMetadata } = require('./modelMetadata');

/**
 * @param {object} p
 * @param {number[][]} p.X   feature matrix (chronologically ordered)
 * @param {number[]}   p.y   HTSI labels (label_source = synthetic_rule)
 * @param {string}     p.datasetName
 * @param {string[]}   p.dataSources
 * @param {number}     [p.testFraction=0.2]
 */
function trainHtsiModel({ X, y, datasetName, dataSources, testFraction = 0.2 }) {
  if (!Array.isArray(X) || X.length < 50) {
    throw new Error(`Not enough training rows (${X ? X.length : 0}); need at least 50.`);
  }
  const splitAt = Math.floor(X.length * (1 - testFraction));
  const Xtrain = X.slice(0, splitAt);
  const ytrain = y.slice(0, splitAt);
  const Xtest = X.slice(splitAt);
  const ytest = y.slice(splitAt);

  const forest = new RandomForestRegression({
    nEstimators: 40,
    maxFeatures: 0.7,
    replacement: true,
    seed: 42,
  });
  forest.train(Xtrain, ytrain);

  const predTest = forest.predict(Xtest);
  const predTrain = forest.predict(Xtrain);

  const metrics = {
    task: 'regression (HTSI score 0–100), risk levels derived for classification view',
    chronologicalSplit: { train: Xtrain.length, test: Xtest.length },
    train: regressionMetrics(ytrain, predTrain),
    test: regressionMetrics(ytest, predTest),
    riskLevelClassification: classificationMetrics(ytest, predTest),
  };

  const prev = loadMetadata();
  const modelVersion = prev ? prev.modelVersion + 1 : 1;
  const metadata = {
    modelType: 'RandomForestRegression (ml-random-forest, Node.js)',
    modelVersion,
    trainingDate: new Date().toISOString(),
    trainingDataset: datasetName,
    features: FEATURE_NAMES,
    target: 'htsi_score',
    labelSource: 'synthetic_rule',
    labelDisclaimer:
      'Labels were generated by the transparent prototype rule engine on synthetic profiles. ' +
      'They are prototype labels, not medical outcomes, and are not medically validated.',
    dataSources,
    hyperparameters: { nEstimators: 40, maxFeatures: 0.7, seed: 42 },
    evaluationMetrics: metrics.test,
  };

  saveModelArtifacts({ modelJson: forest.toJSON(), metadata, metrics });
  return { metadata, metrics };
}

module.exports = { trainHtsiModel };
